name: Compose Docker project

on:
  push:
    branches:
      - main

jobs:
  docker-compose:
    runs-on: self-hosted
    environment: docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Add migration
      #   shell: pwsh
      #   run: |
      #     Add-Migration Init -Project LinhChiDoiSOS.Infrastructure -StartupProject LinhChiDoiSOS.API

      # - name: Update database
      #   shell: pwsh
      #   run: |
      #     Update-database -Project LinhChiDoiSOS.Infrastructure -StartupProject LinhChiDoiSOS.API

      - name: Run Docker compose command
        run: docker compose up --build -d
